Class treinamento.Data.Instrutor Extends (%Persistent, %XML.Adaptor)
{

Storage Default
{
<Data name="InstrutorDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^treinamento.Data.InstrutorD</DataLocation>
<DefaultData>InstrutorDefaultData</DefaultData>
<IdLocation>^treinamento.Data.InstrutorD</IdLocation>
<IndexLocation>^treinamento.Data.InstrutorI</IndexLocation>
<StreamLocation>^treinamento.Data.InstrutorS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
