Class treinamento.Exercicio4
{

ClassMethod Main(matricula As %String, nomeCompleto As %String, Telefone As %String, dataNascimento As %String, sexo As %String)
{
    Write !,"Digite a matricula: " ,matricula
    Write !,"Digite o Nome completo: " ,nomeCompleto
    Write !,"Digite o Telefone: " ,Telefone
    Write !,"Digite a data de nascimento: " ,dataNascimento
    Write !,"Digite o Sexo(M|F): " ,sexo
}

}
